### ISSUE TITLE
Subjoined marks overlap glyphs in following clusters

### ISSUE THREAD

**Issue by dscorbett** [notofonts/cham#7]
### Font 
NotoSansCham-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/cham/releases/tag/NotoSansCham-v2.002
Date: 2022-08-28

### Font version
Version 2.002

### Issue
Subjoined marks can overlap glyphs in following clusters.

### Character data
ꨡꨵꨚ
U+AA21 CHAM LETTER BBA
U+AA35 CHAM CONSONANT SIGN LA
U+AA1A CHAM LETTER PA

ꨆꨵꨪꨚ
U+AA06 CHAM LETTER KA
U+AA35 CHAM CONSONANT SIGN LA
U+AA2A CHAM VOWEL SIGN I
U+AA1A CHAM LETTER PA

### Screenshots
![ꨡꨵꨚ](https://user-images.githubusercontent.com/1124347/187091855-512f6869-d69d-4e59-a874-23201ed01fda.png)
![ꨆꨵꨪꨚ](https://user-images.githubusercontent.com/1124347/187091899-80153325-0751-423b-aa96-9161e5549a95.png)

**Comment by simoncozens** [comment]
I've done what I can with this. There are a few situations where things just about touch (including your first example still) due to the fact that these rules need to be clustered into groups of approximately the same width in order to stop the number of three-glyph kerns from exploding, but the majority of situations are improved.
